import { alt_sc } from "../../../deps.ts";
import {
  ARRAY_DEFINITION_RULE,
  CLASS_DECLARATION_RULE,
  CLASS_DEFINITION_RULE,
  COMPOUND_STATEMENT_RULE,
  COMPUTED_ARRAY_DEFINITION_RULE,
  COMPUTED_ELEMENTARY_TYPE_DEFINITION_RULE,
  ELEMENTARY_TYPE_DEFINITION_RULE,
  EXPRESSION_STATEMENT_RULE,
  MAP_DECLARATION_RULE,
  MAP_DEFINITION_RULE,
  STRING_DEFINITION_RULE,
} from "../syntax_rules.ts";

function getStatementPattern() {
  return alt_sc(
    EXPRESSION_STATEMENT_RULE,
    COMPOUND_STATEMENT_RULE,
    ELEMENTARY_TYPE_DEFINITION_RULE,
    MAP_DECLARATION_RULE,
    MAP_DEFINITION_RULE,
    STRING_DEFINITION_RULE,
    CLASS_DEFINITION_RULE,
    CLASS_DECLARATION_RULE,
    ARRAY_DEFINITION_RULE,
    COMPUTED_ELEMENTARY_TYPE_DEFINITION_RULE,
    COMPUTED_ARRAY_DEFINITION_RULE,
    // TODO: implement below
    // if_statement | switch_statement | for_statement | do_statement | while_statement
  );
}

export default getStatementPattern;
