enum StatementKind {
  ARRAY_DEFINITION,
  COMPUTED_ARRAY_DEFINITION,
  COMPUTED_ELEMENTARY_TYPE_DEFINITION,
  CLASS_DECLARATION,
  CLASS_DEFINITION,
  COMPOUND,
  DO,
  ELEMENTARY_TYPE_DEFINITION,
  EXPRESSION,
  FOR,
  IF,
  MAP_DECLARATION,
  MAP_DEFINITION,
  STRING_DEFINITION,
  SWITCH,
  WHILE,
}

export default StatementKind;
